name: SSH into EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: SSH into EC2 instance
        run: ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" ubuntu@18.184.167.32 
        
