name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2



      - name: Deploy script
        run: |
          ssh -i "$SSH_PRIVATE_KEY" ubuntu@18.196.82.219 'bash -s' << 'EOF'
          python3 /home/ubuntu/calc.py
          EOF

          
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3
