name: SSH into EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/JHKEY.pem
          chmod 600 ~/JHKEY.pem


      - name: SSH into EC2 instance
        run: ssh -i "/home/runner/JHKEY.pem" ubuntu@18.184.167.32 
        
